export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGIN';
export const AUTH_LOGIN_FINISH = 'AUTH_LOGIN_FINISH';
export const AUTH_LOGOUT_FINISH = 'AUTH_LOGOUT_FINISH';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';

export const LOADING_START = 'LOADING_START';
export const LOADING_FINISHED = 'LOADING_FINISHED';

export const GET_USER_INFO = 'GET_USER_INFO';
export const USER_INFO_UPDATE = 'USER_INFO_UPDATE';

export const GET_TASKS = 'GET_TASKS';
export const UPDATE_TASKS = 'UPDATE_TASKS';
